#!/usr/bin/env bash

echo 'Creating necessary directories'

mkdir -v './dist'
mkdir -v './dist/css'
mkdir -v './dist/js'
mkdir -v './dist/favicons'

echo 'Directories created successfully.'


echo 'Minifying HTML files'

minify './src/index.html' > './dist/index.html'
minify './src/web0.html' > './dist/web0.html'

echo 'HTML files successfully minified!'

echo "Minifying CSS files"

minify './src/css/normalize.css' > './dist/css/normalize.css'
minify './src/css/style.css' > './dist/css/style.css'

echo 'CSS files successfully minified!'

echo 'Minifying JS files'

minify './src/js/clip.js' > './dist/js/clip.js'

echo 'JS files successfully minified!'

echo 'Injecting card-html...'

mkdir './tmp'
\sed "\$r ./dist/index.html" ./src/misc/card-html > ./tmp/index.html

mv -f ./tmp/index.html ./dist/index.html
rm -rf ./tmp

echo 'Card inject script executed! 🎉'

echo 'Sorting favicons...'

node ./node_modules/imagemin-cli/cli.js ./src/favicons/*.png --out-dir="./dist/favicons"

cp -v './src/favicons/favicon.ico' './dist'

echo 'Favicons have been minimised!'

echo 'Copying over misc. files'

cp -v './src/misc/card' './dist'
cp -v './src/misc/CNAME' './dist'

echo 'Files copied successfully!'
